# Generated by Django 3.1.5 on 2021-01-29 12:31

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0002_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='description',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
