# Generated by Django 3.1.5 on 2021-01-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0004_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Electronics', 'Electronics'), ('Mobile Device', 'Mobile Device'), ('Computer Device', 'Computer Device')], max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand'), ('Best Seller', 'Best Seller')], max_length=20),
        ),
    ]
