# Generated by Django 3.1.5 on 2021-02-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0005_auto_20210129_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image2',
            field=models.FileField(default='Upload Image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='image3',
            field=models.FileField(default='upload Image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='image4',
            field=models.FileField(default='upload Image', upload_to='images/'),
        ),
    ]
