# Generated by Django 3.1.5 on 2021-02-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0007_contactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Message',
        ),
    ]
