# Generated by Django 3.1.5 on 2021-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0008_auto_20210202_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
