# Generated by Django 3.1.5 on 2021-02-04 15:00

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0010_auto_20210204_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=200)),
                ('Biography', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
