# Generated by Django 3.1.5 on 2021-02-04 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
