# Generated by Django 3.1.5 on 2021-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0012_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default=False, upload_to='images/'),
        ),
    ]
