# Generated by Django 3.1.5 on 2021-02-05 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0013_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='quality',
            new_name='quantity',
        ),
    ]
