# Generated by Django 3.1.5 on 2021-02-09 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0014_auto_20210205_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 15, 38, 59, 142254, tzinfo=utc)),
        ),
    ]
