# Generated by Django 3.1.5 on 2021-02-09 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0015_orderitems_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 15, 41, 2, 245994, tzinfo=utc)),
        ),
    ]
