# Generated by Django 3.1.5 on 2021-02-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0016_auto_20210209_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 8, 53, 29, 66780)),
        ),
    ]
