# Generated by Django 3.1.5 on 2021-02-11 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0018_auto_20210211_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 11, 8, 50, 9, 441479)),
        ),
    ]
