# Generated by Django 3.1.7 on 2021-03-11 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0019_auto_20210211_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='image5',
            field=models.FileField(default='upload Image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='items',
            name='image6',
            field=models.FileField(default='upload Image', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 11, 2, 58, 0, 981955)),
        ),
    ]
