# Generated by Django 3.1.7 on 2021-03-31 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0023_auto_20210330_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 6, 38, 56, 561791)),
        ),
    ]
