# Generated by Django 3.1.7 on 2021-03-31 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0024_auto_20210331_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Electronics', 'Electronics'), ('Mobile Device', 'Mobile Device'), ('Computer Device', 'Computer Device'), ('Home Equipment', 'Home Equipment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Best Seller', 'Best Seller')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 2, 29, 37, 964055)),
        ),
    ]
