# Generated by Django 3.1.7 on 2021-04-01 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0027_auto_20210401_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 5, 1, 38, 249259)),
        ),
    ]
