# Generated by Django 3.1.7 on 2021-04-01 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0028_auto_20210401_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='payment_option',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 5, 33, 26, 396526)),
        ),
    ]
