# Generated by Django 3.1.7 on 2021-04-01 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0030_auto_20210401_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 9, 21, 33, 612396)),
        ),
    ]
