# Generated by Django 3.1.7 on 2021-04-03 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0031_auto_20210401_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 2, 22, 35, 891897)),
        ),
    ]
