# Generated by Django 3.1.7 on 2021-04-03 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0032_auto_20210403_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 2, 43, 52, 429524)),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 2, 43, 52, 428527)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
