# Generated by Django 3.1.7 on 2021-04-03 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0034_auto_20210403_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 4, 0, 18, 535929)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 3, 4, 0, 18, 536926)),
        ),
    ]
