# Generated by Django 3.1.7 on 2021-04-06 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0036_auto_20210403_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Vehicle', 'Vehicle'), ('Electronics', 'Electronics'), ('Mobile Device', 'Mobile Device'), ('Computer Device', 'Computer Device'), ('Home Equipment', 'Home Equipment'), ('Fashion', 'Fashion'), ('Doors', 'Doors'), ('Doors Accessories', 'Doors Accessories'), ('Television', 'Television')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 10, 29, 17, 429555)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 10, 29, 17, 429555)),
        ),
    ]
