# Generated by Django 3.1.7 on 2021-04-07 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0039_auto_20210406_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='availability',
        ),
        migrations.AddField(
            model_name='items',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 46, 46, 830764)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 15, 46, 46, 831762)),
        ),
    ]
