# Generated by Django 3.1.7 on 2021-04-09 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0043_auto_20210406_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 14, 52, 47, 694795)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 14, 52, 47, 696790)),
        ),
    ]
