# Generated by Django 3.1 on 2021-04-12 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0046_auto_20210410_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 18, 40, 16, 832953)),
        ),
    ]
