# Generated by Django 3.1 on 2021-05-22 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0047_auto_20210412_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Electronics', 'Electronics'), ('Mobile Device', 'Mobile Device'), ('Computer Device', 'Computer Device'), ('Home Equipment', 'Home Equipment'), ('Fashion', 'Fashion'), ('Doors', 'Doors'), ('Doors Accessories', 'Doors Accessories'), ('Television', 'Television')], max_length=200)),
                ('label', models.CharField(choices=[('New', 'New'), ('Best Seller', 'Best Seller')], max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='items',
            name='label',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 15, 51, 32, 223520)),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jackhun.category'),
        ),
    ]
