# Generated by Django 3.1 on 2021-05-22 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0048_auto_20210522_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Best Seller', 'Best Seller')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 15, 56, 49, 330054)),
        ),
    ]
