# Generated by Django 3.1 on 2021-05-22 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0050_auto_20210522_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Best Seller', 'Best Seller')], db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 0, 6, 361729)),
        ),
    ]
