# Generated by Django 3.1 on 2021-05-22 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0052_auto_20210522_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 14, 8, 66462)),
        ),
    ]
