# Generated by Django 3.1 on 2021-05-22 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0054_auto_20210522_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('item_name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('item_name',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='label',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=False, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Best Seller', 'Best Seller')], max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 47, 17, 239017)),
        ),
    ]
