# Generated by Django 3.1 on 2021-05-22 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0057_auto_20210522_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='label',
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 56, 0, 71621)),
        ),
    ]
