# Generated by Django 3.1 on 2021-05-22 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jackhun', '0060_auto_20210522_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 17, 7, 23, 206173)),
        ),
        migrations.AlterIndexTogether(
            name='items',
            index_together={('id', 'slug')},
        ),
    ]
