# Generated by Django 3.1.5 on 2021-01-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0005_auto_20210127_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(default='Upload Image', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.FileField(upload_to='media/images'),
        ),
    ]
