# Generated by Django 3.1.5 on 2021-01-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0007_auto_20210129_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Security Door', 'Security Door'), ('Window', 'Window'), ('Door Accessories', 'Door Accessories')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('New', 'New'), ('Second Hand', 'Second Hand'), ('Best Seller', 'Best Seller')], max_length=20),
        ),
    ]
