# Generated by Django 3.1.5 on 2021-02-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0008_auto_20210129_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.FileField(default='Upload Image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.FileField(default='upload Image', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.FileField(default='upload Image', upload_to='images/'),
        ),
    ]
