# Generated by Django 3.1.5 on 2021-02-04 13:13

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0010_emailsubscription_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('full_name', models.CharField(max_length=200)),
                ('Biography', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='leave_a_message',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
