# Generated by Django 3.1.5 on 2021-02-04 13:14

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0011_auto_20210204_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Biography',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
