# Generated by Django 3.1.5 on 2021-02-11 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0014_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
