# Generated by Django 3.1.5 on 2021-02-11 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0015_checkoutaddress_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='time',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
