# Generated by Django 3.1.5 on 2021-02-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0016_auto_20210211_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
