# Generated by Django 3.1.7 on 2021-04-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('michijapp', '0018_auto_20210310_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutAddress',
        ),
    ]
